language: php
php:
  - 7.0
  - 7.1
  - hhvm
matrix:
  allow_failures:
    - php: 7.1
    - php: hhvm
before_install:
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git
  - cd neos-base-distribution
  - git checkout 3.0.0
  - composer update
install:
  - mv ../Nieuwenhuizen.CR Packages/Application
script:
  - bin/phpunit -c Packages/Application/Nieuwenhuizen.CR/UnitTests.xml
  - bin/phpunit --stop-on-failure -c Packages/Application/Nieuwenhuizen.CR/UnitTests.xml --testsuite "Nieuwenhuizen/CR tests"
